# Generated by Django 3.2.5 on 2021-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
