# Generated by Django 3.2.5 on 2021-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfansite', '0004_auto_20210726_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
